---
title: "COVID-19 The World is Not Enough"
author: "David Jackson"
date: "11/04/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(RSQLite)
library(plotly)
```
```{r,echo=FALSE}
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
df <- dbGetQuery(db,"select * from JHUDATA")
df$date <- as.Date(df$date)
df <- df[order(df$date),]

```
```{r}
World <- dbGetQuery(db,"select * from ECDC")
World$Reported <- as.Date(World$Reported,format="%Y-%m-%d")
World <- World[order(World$Reported),]
World <- subset(World,Reported >="2020-03-01")
world_cases <- aggregate(Cases~Reported,World,FUN=sum)
world_deaths <- aggregate(Deaths~Reported,World,FUN=sum)
dbDisconnect(db)
```

### Total Cases and Deaths by Country

```{r}
df <- subset(df,date =="2020-10-31")
df$Rate <- df$deaths/df$confirmed
# df <- df[order(df$Rate),]
# df$Row <- row.names(df)
df_lt <- subset(df,Rate <=0.024)
df_gt <- subset(df, Rate >=0.0241)
```

### Plot Death Rate by Country

```{r}
ggplot(df_gt) + geom_col(aes(x=reorder(country,Rate),y=Rate)) + coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  geom_hline(yintercept = 0.025,col="red") +
  labs(title="Countries with Deaths >=2.41%")

ggplot(df_lt) + geom_col(aes(x=reorder(country,Rate),y=Rate)) + coord_flip() +
  scale_y_continuous(labels = scales::percent) +
  geom_hline(yintercept = 0.025,col="red") +
  labs(title="Countries with Death Rates <= 2.4%") 


```

## Daily Cases and Deaths for the World

```{r}
ggplot(world_cases) + geom_line(aes(x=Reported,y=Cases)) +
  geom_smooth(aes(x=Reported,y=Cases),span=0.25) +
  labs(title="World Wide Covid19 Cases by Day.")
```
```{r}
ggplot(world_deaths) + geom_line(aes(x=Reported,y=Deaths)) +
  geom_smooth(aes(x=Reported,y=Deaths),span=0.25) +
  labs(title="World Wide Covid19 Deaths by Day.")

```

